services:
  backend:
    build:
      context: ./backend
    container_name: website_backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [mdms_webnet]

  frontend:
    build:
      context: ./frontend
    container_name: website_frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy    # ★ 等後端健康
    networks: [mdms_webnet]


networks:
  mdms_webnet:
    driver: bridge

